### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by xjcvip007** [mf-zhang/GazeOnce#1]
Thanks for amazing job~ Any code release plan?

**Comment by wenzhengzeng** [comment]
Thanks for your great work. Can you give an approximate date for training & test code release?

**Comment by mf-zhang** [comment]
Sorry that we cannot release our code or model now. With our released data, most of our results should be easily reproduced following our paper and a face detection model, such as [this](https://github.com/biubug6/Pytorch_Retinaface).
