### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Helenailse1** [mf-zhang/GazeOnce#5]
Thanks for your great work. Can you give an approximate date for training & test code release?

**Comment by mf-zhang** [comment]
Sorry that we cannot release our code or model now. With our released data, most of our results should be easily reproduced following our paper and a face detection model, such as [this](https://github.com/biubug6/Pytorch_Retinaface).

**Comment by Helenailse1** [comment]
Thank you for your answer. We submitted a data request but it was not approved

**Comment by mf-zhang** [comment]
If all the necessary information has been provided and the approval has not been granted, I'm sorry that I'm not authorized to approve it...

**Comment by YuXiangLin1234** [comment]
Hello, I try to reproduce your great work based on the github repo you mentioned before, but results seems to be not good. I'm new to object detection, so there may be some errors in my code. I want to clarify two things:

1. In SSD, we have to encode the variance from priorbox when computing losses of face location & landmark and then decode it. I'm not sure if there any way to encode gaze yaw and pitch (They are neither in point-form or center-form), or we don't have to encode gaze just as encoding landmark and location at all?  
2. For downstream gaze head, can I just copy the architecture of location head & landmark head?
```
class LandmarkHead(nn.Module):
    def __init__(self,inchannels=512,num_anchors=3):
        super(LandmarkHead,self).__init__()
        self.conv1x1 = nn.Conv2d(inchannels,num_anchors*10,kernel_size=(1,1),stride=1,padding=0) -------------------------> output 5 landmark
    def forward(self,x):
        out = self.conv1x1(x)
        out = out.permute(0,2,3,1).contiguous()

        return out.view(out.shape[0], -1, 10)

class GazeHead(nn.Module):
    def __init__(self,inchannels=512,num_anchors=3):
        super(GazeHead,self).__init__()
        self.conv1x1 = nn.Conv2d(inchannels,num_anchors*2,kernel_size=(1,1),stride=1,padding=0) --------------------------> output pitch and yaw

    def forward(self,x):
        out = self.conv1x1(x)
        out = out.permute(0,2,3,1).contiguous()

        return out.view(out.shape[0], -1, 2)
```

Thank you for any help you can provide.
