### ISSUE TITLE
对比实验似乎不够充分

### ISSUE THREAD

**Issue by AaboutL** [mf-zhang/GazeOnce#7]
作者您好，
感觉文章中视线模块的设计挺好，但是最后的实验分析好像不太充分，没有在开源数据上与其他的视线估计方法做对比。请问您内部有没有做过这方面的比较呢

**Comment by mf-zhang** [comment]
您好，谢谢您对这个工作的关注。因为在投稿时没有开源数据中有在同一张图像上有多个有gaze标签的人物出现，所以我们无法做比较。与其他方法的比较只能在本文中的数据集上做了测试，这确实有局限性。
